!!python/object:argparse.Namespace
alpha: 0.1
batch_size: 32
device: cpu
epochs: 1
input_size: 8
latent_size: 6
lr: 0.01
no_progress_bar: false
num_resamples: 5
num_tests: 1
steps_log_loss: 1000
steps_log_norm_params: 1000
test_name: test shell 1
