!!python/object:argparse.Namespace
alpha: 0.5
batch_size: 10
device: cpu
epochs: 10
input_size: 8
latent_size: 6
lr: 0.001
no_progress_bar: false
num_resamples: 10
num_tests: 5
steps_log_loss: 1000
steps_log_norm_params: 1000
test_name: VAE-IDS-test}
